
exclude:
  - "/vendor/"
  - "Gemfile"
  - "Gemfile.lock"
  - "README.md"
  - "LICENSE.md"
  - "*.gemspec"

keep_files:
  - "CNAME"
  - ".git"
  - ".gitignore"


# Site settings
title: "CLIFTN: Light Electric BMX and Road Bikes"
subtitle: "Electric BMX Bikes and Light Electric Road Bikes"

# For testing locally
#url: "/"                    # the base hostname & protocol for your site
#baseurl: "/cliftn_site"

# For deployment
url: "https://cliftn.com"  # the base hostname & protocol for your site
baseurl: "/"

cover: "/assets/cover.png"
logo: "/assets/logo.png" 

description: "We are developing state-of-the-art electric bikes.  Check out our latest Electric BMX and Light Electric Road Bikes!"
permalink: /:title/

# Build settings
markdown: kramdown

# Google analytics
ga_tracking_id: "UA-154009840-2"

# Category descriptions (for archive pages)
descriptions:
  - cat: jekyll
    desc: "Posts describing Jekyll setup techniques."

  - cat: dummy
    desc: "Just some placeholder posts, lorem ipsum and the rest."


plugins:
  - jekyll-sitemap